Mode: debug
Host: "127.0.0.1"
Port: "8080"
Log:
    LogPath: "./latest.log"
    CLS:
        Endpoint: ""
        AccessKey: ""
        AccessToken: ""
        TopicID: ""
Postgres:
    Addr: "127.0.0.1"
    Port: "5432"
    User: "grpc-template-service"
    Password: "123456"
    Database: "grpc-template-service"
    UseSSL: "disable"
    Debug: false
Redis:
    Addr: "127.0.0.1"
    Port: "5432"
    Password: ""
    Db: 0
B2:
    BucketKeyID: ""
    BucketKey: ""
    BucketName: ""
SentryDsn: ""
hduhelp:
    ClientID: ""
    ClientSecret: ""
    OauthFinishPath: ""
OTel:
    Enable: false
    ServiceName: "grpc-template-service"
    ServiceVersion: "v1.0.0"
    AgentHost: "127.0.0.1"
    AgentPort: "4318"
